ci: Expand test matrices.
stickeeuk/canary pull request #21
Opened 2023-01-03 10:53 UTC by stickeeoliver

2023-01-03 10:58 UTC, stickeeoliver commented
Looks like we have failing tests... best to get these resolved first before expanding testing matrix.

2023-01-03 13:03 UTC, stickeeoliver commented
Shelving this until PHP CS Fixer officially supports 8.2.

2023-01-03 13:04 UTC, stickeepaul commented
`https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6714#issuecomment-1359166470`

> PHP CS Fixer is not ready to run on 8.2.

we'll need to wait a bit more

2023-03-16 16:22 UTC, stickeepaul requested changes

2023-03-16 16:22 UTC, stickeepaul commented on .github/workflows/tests.yaml
> +        os: [ ubuntu-latest, macos-latest, windows-latest ]
```suggestion
        os: [ ubuntu-latest ]
```
let's drop MacOS and Windows

2023-03-16 16:22 UTC, stickeepaul commented
PHP CS fixer now supports PHP 8.2
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/tag/v3.15.0

2023-03-16 16:39 UTC, stickeepaul approved these changes

2023-03-16 16:40 UTC, merged

2023-03-16 16:40 UTC, stickeepaul commented
:tada: This PR is included in version 2.0.6 :tada:

The release is available on [GitHub release](https://github.com/stickeeuk/canary/releases/tag/v2.0.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: